version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
hooks:
  BeforeInstall
    - location: scripts/cleanup
      runas: root
  ApplicationStart
    - location: scripts/restart
      runas: root
